language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install:
  - python setup.py install
  - if [[ $FULL == 'true' && $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install 'zope.interface<4.0'; fi
  - pip install werkzeug pytest sqlalchemy suds msgpack-python
script: python setup.py test
