language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install:
  - python setup.py install
  - if [[ $FULL == 'true' ]]; then if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors 'twisted<12' 'zope.interface<4.0' 'pyzmq<2.2' multiprocessing; else pip install --use-mirrors twisted pyzmq; fi; fi
  - pip install werkzeug pytest sqlalchemy suds msgpack-python
script: python setup.py test
